### ISSUE TITLE
logo proposal

### ISSUE THREAD

**Issue by ritalinn** [cauebs/durt#7]
I designed a logo that is compatible with the project. Would you like to use it? I designed it voluntarily.

![durt](https://user-images.githubusercontent.com/41344739/42971065-b5a4c048-8bb3-11e8-8b76-4a834b24d92f.jpg)

**Comment by dlight** [comment]
What's the license on it? I suggest some creative commons license.

**Comment by cauebs** [comment]
Pretty cool! Would you like to open a PR adding it to the `README.md` file?
You can either host it somewhere else or add it directly to this repo, under a `docs` directory, for example.

**Comment by ritalinn** [comment]
I sent the necessary files. I'm open pr.
